config/routes.rb
Rails.application.routes.draw do
  resources :advertisements
  resources :profiles
  get 'ad/home'

  devise_for :users

   root 'ad#home'

end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
  belongs_to :profile
end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/ad_controller.rb
class AdController < ApplicationController
  def home

@ads=Advertisement.select("id","profile_id",'atype',"name","cost","acost","bcost","balance","active","date").all

  end
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  before_action :set_advertisement, only: [:show, :edit, :update, :destroy]

  # GET /advertisements
  # GET /advertisements.json
  def index
    @advertisements = Advertisement.all
  end

  # GET /advertisements/1
  # GET /advertisements/1.json
  def show
  end

  # GET /advertisements/new
  def new
    @advertisement = Advertisement.new
  end

  # GET /advertisements/1/edit
  def edit
  end

  # POST /advertisements
  # POST /advertisements.json
  def create
    @advertisement = Advertisement.new(advertisement_params)

    respond_to do |format|
      if @advertisement.save
        format.html { redirect_to @advertisement, notice: 'Advertisement was successfully created.' }
        format.json { render :show, status: :created, location: @advertisement }
      else
        format.html { render :new }
        format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advertisements/1
  # PATCH/PUT /advertisements/1.json
  def update
    respond_to do |format|
      if @advertisement.update(advertisement_params)
        format.html { redirect_to @advertisement, notice: 'Advertisement was successfully updated.' }
        format.json { render :show, status: :ok, location: @advertisement }
      else
        format.html { render :edit }
        format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertisements/1
  # DELETE /advertisements/1.json
  def destroy
    @advertisement.destroy
    respond_to do |format|
      format.html { redirect_to advertisements_url, notice: 'Advertisement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertisement
      @advertisement = Advertisement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertisement_params
      params.require(:advertisement).permit(:profile_id, :name, :atype, :cost, :acost, :bcost, :active, :balance, :date, :due, :howmany)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

before_filter :authenticate_user!


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :cname, :addr, :mob)
    end
end

app/helpers/ad_helper.rb
module AdHelper
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
 
 def is_active(path)
   if current_page?(path) 
   	"sideactive"
   else
   	 "side-link"
	end
 end
 def is_nameit()
 	d={'profiles'=>"Customer",'advertisements'=>"Advertisement",'ad'=>"Home"}
 
 	s=d[params[:controller]].to_s
 	
 end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/ad/home.html.erb
<script type="text/javascript">
  var app=angular.module('ad',[])
app.controller('m', function($scope) {

  $scope.s=<%=@ads.to_json.html_safe%>; 
  

});

</script>
       

      <main ng-app="ad" ng-controller="m">







<div class="container-fluid" >
    <div class="row">
    <div class="col m12 s12">



        <div class="card grey lighten-4">
            <div class="card-content">
    
               <div class="row">
                  <div class="col m3 s3">
                    <input id="search" type="text" placeholder="Search" ng-model="se" required>
                  </div>

                  <div class="col m3 s3">
                                <br><br><div class="switch"><label><input id="l"type="checkbox" ng-false-value=""ng-true-value="<%=Time.now.strftime("%d ")%>" ng-model="ss.date" checked><span class="lever"></span></label>
                          <label for="l"> Today</label>
                  </div>
              
                 
               </div> 
    <div class="row">

                  <div class="input-field col m6 s6">
          <input id="tcost" type="date" name="advertisement[date]" ng-model="hh.date" >

          <label for="tcost"></label>
<h1 style="color:red;">{{hh.date|date}}</h1>

          
        </div>                    


                  </div>
  




            </div>
        </div>
    </div>
    </div>
</div>




    <div class="container-fluid" >
    <div class="row">
    <div class="col m12 s12">

        <div class="card grey lighten-4">
            <div class="card-content">
              <div class="row">
                  {{s}}


                
              </div>
        <table class="highlight centered bordered">
        <thead>
          <tr>
              <th data-field="id">Name <br><br></th>
              <th data-field="id">Type 
                        <br><br><div class="switch"><label><input type="checkbox" ng-false-value="Roller" ng-true-value="Video" ng-model="ss.atype" checked><span class="lever"></span></label></div>
              </th>
              <th data-field="id">Active
                <br><br><div class="switch"><label><input type="checkbox" ng-model="ss.active" checked><span class="lever"></span></label></div>
              </th>
              <th data-field="id">Balance
                    <br><br><div class="switch"><label><input type="checkbox" ng-model="ss.balance" checked><span class="lever"></span></label></div>
              </th>


          </tr>
        </thead>

        <tbody>
          
        
          <tr ng-repeat="i in s |filter:se | filter:ss">
            <td><a href="/advertisements/{{i.id}}">{{i.name}}</a></td>
            
            <td></td>
            <td>
            <div class="switch"><label><input type="checkbox" checked><span class="lever"></span></label></div>
            </td>
            <td>
            <div class="switch"><label><input type="checkbox" value=""checked><span class="lever"></span></label></div>
            </td>
            
          </tr>
        
        </tbody>
      </table>
           
           
           
           
            </div>
        </div>
    </div>
    </div>
    </div>

<script type="text/javascript">
  $('.datepicker').pickadate({
    selectMonth:true
  });
</script>
        
    </main>
      
       
        

app/views/advertisements/_form.html.erb
<%= form_for(@advertisement) do |f| %>
  <% if @advertisement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advertisement.errors.count, "error") %> prohibited this advertisement from being saved:</h2>

      <ul>
      <% @advertisement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :profile_id %><br>
    <%= f.text_field :profile_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :atype %><br>
    <%= f.text_field :atype %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
  </div>
  <div class="field">
    <%= f.label :acost %><br>
    <%= f.number_field :acost %>
  </div>
  <div class="field">
    <%= f.label :bcost %><br>
    <%= f.number_field :bcost %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :balance %><br>
    <%= f.check_box :balance %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :due %><br>
    <%= f.text_field :due %>
  </div>
  <div class="field">
    <%= f.label :howmany %><br>
    <%= f.text_field :howmany %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/advertisements/edit.html.erb
<h1>Editing Advertisement</h1>

<%= render 'form' %>

<%= link_to 'Show', @advertisement %> |
<%= link_to 'Back', advertisements_path %>

app/views/advertisements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Advertisements</h1>

<table>
  <thead>
    <tr>
      <th>Profile</th>
      <th>Name</th>
      <th>Atype</th>
      <th>Cost</th>
      <th>Acost</th>
      <th>Bcost</th>
      <th>Active</th>
      <th>Balance</th>
      <th>Date</th>
      <th>Due</th>
      <th>Howmany</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advertisements.each do |advertisement| %>
      <tr>
        <td><%= advertisement.profile %></td>
        <td><%= advertisement.name %></td>
        <td><%= advertisement.atype %></td>
        <td><%= advertisement.cost %></td>
        <td><%= advertisement.acost %></td>
        <td><%= advertisement.bcost %></td>
        <td><%= advertisement.active %></td>
        <td><%= advertisement.balance %></td>
        <td><%= advertisement.date %></td>
        <td><%= advertisement.due %></td>
        <td><%= advertisement.howmany %></td>
        <td><%= link_to 'Show', advertisement %></td>
        <td><%= link_to 'Edit', edit_advertisement_path(advertisement) %></td>
        <td><%= link_to 'Destroy', advertisement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advertisement', new_advertisement_path %>

app/views/advertisements/new.html.erb
<h1>New Advertisement</h1>

<%= render 'form' %>

<%= link_to 'Back', advertisements_path %>

app/views/advertisements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Profile:</strong>
  <%= @advertisement.profile %>
</p>

<p>
  <strong>Name:</strong>
  <%= @advertisement.name %>
</p>

<p>
  <strong>Atype:</strong>
  <%= @advertisement.atype %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @advertisement.cost %>
</p>

<p>
  <strong>Acost:</strong>
  <%= @advertisement.acost %>
</p>

<p>
  <strong>Bcost:</strong>
  <%= @advertisement.bcost %>
</p>

<p>
  <strong>Active:</strong>
  <%= @advertisement.active %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @advertisement.balance %>
</p>

<p>
  <strong>Date:</strong>
  <%= @advertisement.date %>
</p>

<p>
  <strong>Due:</strong>
  <%= @advertisement.due %>
</p>

<p>
  <strong>Howmany:</strong>
  <%= @advertisement.howmany %>
</p>

<%= link_to 'Edit', edit_advertisement_path(@advertisement) %> |
<%= link_to 'Back', advertisements_path %>

app/views/layouts/application.html.erb
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


<% if user_signed_in? %>
<!-- 
###########################After login Goes Here########################## -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Home | Priya TV</title>

    <link href="/assets/css/materialize.min.css" rel="stylesheet">
    <link href="/assets/css/style.css" rel="stylesheet">
    <link href="/assets/fonts/roboto/stylesheet.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%@menu='home'%>
</head>
<body>
   <header>
   <div class="navbar-fixed">
    <nav  class="top-nav">
      <div class="nav-wrapper">
              <a class="brand-logo logopad">Priya TV - <%=is_nameit()%>  </a>
               <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
          <ul class="right "><li><%= link_to('Logout', destroy_user_session_path, :method => :delete,:class=>"waves-effect waves-light btn") %></li></ul>
      
      </div>
    </nav>
  </div>
        
      <ul id="mobile-demo" class="side-nav fixed">

          <div class="navmar">
          <a class="<%=is_active(ad_home_path)%>" href="<%=ad_home_path%>" >
          <li class="side-link"><i class="material-icons">home</i>Home</li></a>
          
          <a href="<%=profiles_path%>">
          <li class="<%=is_active(profiles_path)%>"><i class="material-icons">supervisor_account</i>Customer</li></a>
          
          <a href="<%=advertisements_path%>">
          <li class="<%=is_active(advertisements_path)%>"><i class="material-icons">list</i>Advertisement</li></a>

</div>
      </ul>
</header>

<%= yield %>
<!-- 
###############################Footer############################################# -->
    <footer>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <ul class="flist">
                        <li class="li"><a href="#" class="waves-effect waves-teal btn-flat">About Us</a></li>
                        <li class="li"><a href="#" class="waves-effect waves-teal btn-flat">Privacy</a></li>
                        <li class="li"><a href="#" class="waves-effect waves-teal btn-flat">Terms</a></li>
                        <li class="li"><a href="#" class="waves-effect waves-teal btn-flat">Help</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>


<script src="js/jquery.min.js"></script>
<script src="js/materialize.min.js"></script>
 
<script type="text/javascript">
        
    $('.button-collapse').sideNav({
      menuWidth: 260, 
      edge: 'left'
    });
        
        $(document).ready(function(){
    $('.collapsible').collapsible({
      accordion : false 
    });
  });
        
        $(document).ready(function() {
    $('select').material_select();
  });
      </script>

<!-- 
###############################Footer############################################# -->




</body>
</html>

<!-- 
#####################Before Login Goes here ################################# -->
<%else%>


	<%=yield%>
	
<%end%>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cname %><br>
    <%= f.text_field :cname %>
  </div>
  <div class="field">
    <%= f.label :addr %><br>
    <%= f.text_field :addr %>
  </div>
  <div class="field">
    <%= f.label :mob %><br>
    <%= f.text_field :mob %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cname</th>
      <th>Addr</th>
      <th>Mob</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.cname %></td>
        <td><%= profile.addr %></td>
        <td><%= profile.mob %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Cname:</strong>
  <%= @profile.cname %>
</p>

<p>
  <strong>Addr:</strong>
  <%= @profile.addr %>
</p>

<p>
  <strong>Mob:</strong>
  <%= @profile.mob %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>